# Site settings
title: Ilia Lebedev
author: Ilia Lebedev
email: ilebedev@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a professional and personal site for Ilia Lebedev, a PhD student at
  <a href="http://mit.edu">MIT</a>
  <a href="https://www.csail.mit.edu/">CSAIL</a>
  working with prof.
  <a href="http://people.csail.mit.edu/devadas/">Srini Devadas</a>
  in the area of computer security.
  In my little free time, I am a sailing vessel captain, bartender, and a few
  other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ilebedev.github.io" # the base hostname & protocol for your site
github_username:  ilebedev
linkedin_username: ilialebedev

# Build settings
markdown: kramdown
